name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem statement
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
    validations:
      required: true
